# Mapping of common ports to services

COMMON_PORTS = {
    20: "FTP (Data)",
    21: "FTP (Control)",
    22: "SSH",
    23: "Telnet",
    25: "SMTP (Simple Mail Transfer Protocol)",
    53: "DNS (Domain Name System)",
    67: "DHCP (Dynamic Host Configuration Protocol) Server",
    68: "DHCP (Dynamic Host Configuration Protocol) Client",
    69: "TFTP (Trivial File Transfer Protocol)",
    80: "HTTP (Hypertext Transfer Protocol)",
    110: "POP3 (Post Office Protocol version 3)",
    123: "NTP (Network Time Protocol)",
    135: "Microsoft RPC (Remote Procedure Call)",
    137: "NetBIOS Name Service",
    138: "NetBIOS Datagram Service",
    139: "NetBIOS Session Service",
    143: "IMAP (Internet Message Access Protocol)",
    161: "SNMP (Simple Network Management Protocol)",
    162: "SNMP Trap",
    179: "BGP (Border Gateway Protocol)",
    389: "LDAP (Lightweight Directory Access Protocol)",
    443: "HTTPS (HTTP Secure)",
    445: "SMB (Server Message Block) over TCP",
    465: "SMTPS (SMTP Secure)",
    513: "rlogin",
    514: "syslog",
    636: "LDAPS (LDAP over TLS/SSL)",
    993: "IMAPS (IMAP Secure)",
    995: "POP3S (POP3 Secure)",
    1433: "Microsoft SQL Server",
    1521: "Oracle SQL",
    2049: "NFS (Network File System)",
    3306: "MySQL",
    3389: "Remote Desktop Protocol (RDP)",
    5432: "PostgreSQL",
    5900: "VNC (Virtual Network Computing)",
    6379: "Redis",
    8080: "HTTP Alternate",
}
